/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AddCount: typeof import('../state/count.svelte').AddCount
  const C: typeof import('../utils/check').C
  const CheckJson: typeof import('../utils/check').CheckJson
  const TestUtil: typeof import('../utils/ParseJson').TestUtil
  const TypeCheckJson: typeof import('../utils/TypeCheckJson').TypeCheckJson
  const afterUpdate: typeof import('svelte').afterUpdate
  const beforeUpdate: typeof import('svelte').beforeUpdate
  const count: typeof import('../../routes/count.svelte').count
  const counter: typeof import('../state/count.svelte').counter
  const createEventDispatcher: typeof import('svelte').createEventDispatcher
  const getAllContexts: typeof import('svelte').getAllContexts
  const getContext: typeof import('svelte').getContext
  const goto: typeof import('@sveltejs/kit').goto
  const hasContext: typeof import('svelte').hasContext
  const invalidate: typeof import('@sveltejs/kit').invalidate
  const invalidateAll: typeof import('@sveltejs/kit').invalidateAll
  const onDestroy: typeof import('svelte').onDestroy
  const onMount: typeof import('svelte').onMount
  const preloadCode: typeof import('@sveltejs/kit').preloadCode
  const preloadData: typeof import('@sveltejs/kit').preloadData
  const setContext: typeof import('svelte').setContext
  const tick: typeof import('svelte').tick
  const toast: typeof import('../utils/swal.js').toast
}
