/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const CheckJson: typeof import('../utils/check').CheckJson
  const DashboardState: typeof import('../stores/dashboard.svelte').DashboardState
  const afterUpdate: typeof import('svelte').afterUpdate
  const autoTabCloak: typeof import('../utils/cloak').autoTabCloak
  const beforeUpdate: typeof import('svelte').beforeUpdate
  const cn: typeof import('../utils/cn').cn
  const createEventDispatcher: typeof import('svelte').createEventDispatcher
  const dashboard: typeof import('../stores/dashboard.svelte').dashboard
  const devTools: typeof import('../stores/DevTools.svelte').devTools
  const getAllContexts: typeof import('svelte').getAllContexts
  const getContext: typeof import('svelte').getContext
  const goto: typeof import('@sveltejs/kit').goto
  const hasContext: typeof import('svelte').hasContext
  const invalidate: typeof import('@sveltejs/kit').invalidate
  const invalidateAll: typeof import('@sveltejs/kit').invalidateAll
  const isEnvDevPublic: typeof import('../stores/DevTools.svelte').isEnvDevPublic
  const onDestroy: typeof import('svelte').onDestroy
  const onMount: typeof import('svelte').onMount
  const preloadCode: typeof import('@sveltejs/kit').preloadCode
  const preloadData: typeof import('@sveltejs/kit').preloadData
  const setContext: typeof import('svelte').setContext
  const tick: typeof import('svelte').tick
  const toast: typeof import('../utils/toast').toast
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FileNode } from '../stores/DevTools.svelte'
  import('../stores/DevTools.svelte')
  // @ts-ignore
  export type { DashboardState, DeletedItem } from '../stores/dashboard.svelte'
  import('../stores/dashboard.svelte')
}
