// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const AddGamesModal: typeof import("./../components/AddGamesModal.svelte")["default"]
    const GameCard: typeof import("./../components/GameCard.svelte")["default"]
    const GameViewer: typeof import("./../components/GameViewer.svelte")["default"]
    const Navbar: typeof import("./../components/Navbar.svelte")["default"]
    const SettingsView: typeof import("./../components/SettingsView.svelte")["default"]
}

export {}
